ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "mileage" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "insured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "registered" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "parkedAt" TEXT;

CREATE TABLE IF NOT EXISTS "PlayerBusiness" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"businessId" TEXT NOT NULL UNIQUE,"name" TEXT NOT NULL,"type" TEXT NOT NULL,"district" TEXT NOT NULL,"level" INTEGER NOT NULL DEFAULT 1,"reputation" INTEGER NOT NULL DEFAULT 50,"revenue" INTEGER NOT NULL DEFAULT 0,"expenses" INTEGER NOT NULL DEFAULT 0,"balance" INTEGER NOT NULL DEFAULT 0,"staff" INTEGER NOT NULL DEFAULT 0,"menu" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE INDEX IF NOT EXISTS "PlayerBusiness_userId_idx" ON "PlayerBusiness"("userId");
CREATE INDEX IF NOT EXISTS "PlayerBusiness_district_type_idx" ON "PlayerBusiness"("district","type");
CREATE TABLE IF NOT EXISTS "CareerProgress" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"profession" TEXT NOT NULL,"title" TEXT NOT NULL,"rank" INTEGER NOT NULL DEFAULT 1,"xp" INTEGER NOT NULL DEFAULT 0,"completed" INTEGER NOT NULL DEFAULT 0,"salaryBonus" INTEGER NOT NULL DEFAULT 0,"unlockedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "CareerProgress_userId_profession_key" ON "CareerProgress"("userId","profession");
CREATE TABLE IF NOT EXISTS "Reputation" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL UNIQUE,"score" INTEGER NOT NULL DEFAULT 50,"trust" INTEGER NOT NULL DEFAULT 50,"crime" INTEGER NOT NULL DEFAULT 0,"social" INTEGER NOT NULL DEFAULT 50,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE IF NOT EXISTS "CityEvent" ("id" TEXT PRIMARY KEY,"key" TEXT NOT NULL UNIQUE,"title" TEXT NOT NULL,"description" TEXT NOT NULL,"district" TEXT NOT NULL,"kind" TEXT NOT NULL,"intensity" INTEGER NOT NULL DEFAULT 1,"startsAt" TIMESTAMP(3) NOT NULL,"endsAt" TIMESTAMP(3) NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"data" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS "CityEvent_active_startsAt_endsAt_idx" ON "CityEvent"("active","startsAt","endsAt");
CREATE INDEX IF NOT EXISTS "CityEvent_district_active_idx" ON "CityEvent"("district","active");
CREATE TABLE IF NOT EXISTS "CityBusinessMetric" ("id" TEXT PRIMARY KEY,"businessId" TEXT NOT NULL,"dayKey" TEXT NOT NULL,"visitors" INTEGER NOT NULL DEFAULT 0,"revenue" INTEGER NOT NULL DEFAULT 0,"incidents" INTEGER NOT NULL DEFAULT 0,"rating" INTEGER NOT NULL DEFAULT 50,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "CityBusinessMetric_businessId_dayKey_key" ON "CityBusinessMetric"("businessId","dayKey");
ALTER TABLE "PlayerBusiness" ADD CONSTRAINT "PlayerBusiness_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CareerProgress" ADD CONSTRAINT "CareerProgress_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Reputation" ADD CONSTRAINT "Reputation_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
