'use client';
import dynamic from 'next/dynamic';
import { useEffect, useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import type { District, PlayerLook } from '../components/World';

const World = dynamic(() => import('../components/World'), { ssr: false, loading: () => <div className="canvasLoading">Loading Abuja 3D world…</div> });

type Tab='home'|'phone'|'jobs'|'bank'|'map'|'profile';
type Game={name:string;cash:number;bank:number;energy:number;mood:number;health:number;fitness:number;hunger:number;district:District;day:number;hour:number;job:string;level:number;xp:number;rentPaid:boolean;inventory:string[];missions:string[];feed:string[];look:PlayerLook;property:string;car:string};
const initial:Game={name:'David',cash:42500,bank:85000,energy:76,mood:82,health:96,fitness:61,hunger:72,district:'Wuse',day:1,hour:8,job:'Freelancer',level:1,xp:20,rentPaid:false,inventory:['Phone','Backpack'],missions:['Complete your first work shift','Visit Jabi Lake','Save ₦100,000'],feed:['You arrived in Abuja and rented a starter apartment.','Your first day begins in Wuse.'],look:{skin:'#8b552f',shirt:'#126c4b',pants:'#222831',hair:'#151515'},property:'Starter Apartment',car:'None'};
const jobs=[{name:'Hotel Receptionist',pay:9500,energy:18,xp:25},{name:'Social Media Manager',pay:13000,energy:22,xp:35},{name:'Ride Driver',pay:11000,energy:26,xp:28},{name:'Graphic Designer',pay:15500,energy:20,xp:40},{name:'Software Developer',pay:22000,energy:24,xp:55}];
const properties=[{name:'Wuse Studio',price:650000,comfort:8},{name:'Jabi Apartment',price:1400000,comfort:14},{name:'Gwarinpa 2-Bed',price:2200000,comfort:20},{name:'Maitama Luxury Flat',price:8500000,comfort:35}];
const cars=[{name:'Keke',price:450000,comfort:4},{name:'Toyota Corolla',price:4800000,comfort:10},{name:'Lexus RX',price:14500000,comfort:18}];
function money(n:number){return `₦${Math.max(0,Math.round(n)).toLocaleString()}`}
function clamp(n:number){return Math.max(0,Math.min(100,n))}
export default function Home(){
 const [g,setG]=useState<Game>(initial); const [tab,setTab]=useState<Tab>('home'); const [moving,setMoving]=useState(false); const [notice,setNotice]=useState('Welcome to Abuja. Your story starts now.');
 useEffect(()=>{const saved=localStorage.getItem('abuja-real-life-save');if(saved)try{setG({...initial,...JSON.parse(saved)})}catch{}},[]);
 useEffect(()=>{localStorage.setItem('abuja-real-life-save',JSON.stringify(g))},[g]);
 const time=useMemo(()=>`${String(Math.floor(g.hour)).padStart(2,'0')}:00`,[g.hour]);
 function log(text:string){setG(v=>({...v,feed:[text,...v.feed].slice(0,10)}));setNotice(text)}
 function advance(hours=1){setG(v=>({...v,hour:(v.hour+hours)%24,day:v.hour+hours>=24?v.day+1:v.day,energy:clamp(v.energy-(hours*2)),hunger:clamp(v.hunger-(hours*3))}))}
 function work(job=jobs.find(j=>j.name===g.job)||jobs[0]){if(g.energy<15||g.hunger<15){log('You are too tired or hungry to work. Eat or rest first.');return}setG(v=>({...v,cash:v.cash+job.pay,energy:clamp(v.energy-job.energy),mood:clamp(v.mood+2),hunger:clamp(v.hunger-8),xp:v.xp+job.xp}));advance(4);log(`You completed a ${job.name} shift and earned ${money(job.pay)}.`)}
 function eat(){const cost=1800;if(g.cash<cost){log('You cannot afford a meal.');return}setG(v=>({...v,cash:v.cash-cost,hunger:clamp(v.hunger+30),energy:clamp(v.energy+8),mood:clamp(v.mood+4)}));advance(.5);log(`You ate at a local spot. -${money(cost)}`)}
 function rest(){setG(v=>({...v,energy:clamp(v.energy+45),health:clamp(v.health+8),mood:clamp(v.mood+6),hunger:clamp(v.hunger-12)}));advance(7);log('You rested at home and recovered.');}
 function gym(){if(g.energy<12){log('You need more energy for the gym.');return}setG(v=>({...v,energy:clamp(v.energy-12),fitness:clamp(v.fitness+7),mood:clamp(v.mood+5),health:clamp(v.health+2),xp:v.xp+10}));advance(1);log('You trained at the gym. Fitness +7.');}
 function travel(d:District){if(d===g.district)return;const cost=700;if(g.cash<cost){log('Not enough cash for transport.');return}setG(v=>({...v,cash:v.cash-cost,district:d,energy:clamp(v.energy-4),mood:clamp(v.mood+2)}));advance(1);log(`You travelled to ${d}. Transport cost ${money(cost)}.`)}
 function deposit(){const n=Math.min(g.cash,10000);if(!n){log('No cash available to deposit.');return}setG(v=>({...v,cash:v.cash-n,bank:v.bank+n}));log(`Deposited ${money(n)} into your bank account.`)}
 function withdraw(){const n=Math.min(g.bank,10000);if(!n){log('Your bank balance is empty.');return}setG(v=>({...v,cash:v.cash+n,bank:v.bank-n}));log(`Withdrew ${money(n)} from your bank.`)}
 function buyProperty(p:{name:string;price:number;comfort:number}){if(g.cash<p.price){log('You cannot afford this property yet.');return}setG(v=>({...v,cash:v.cash-p.price,property:p.name,energy:clamp(v.energy+p.comfort),mood:clamp(v.mood+10)}));log(`You bought ${p.name} for ${money(p.price)}.`)}
 function buyCar(c:{name:string;price:number}){if(g.cash<c.price){log('You cannot afford this vehicle yet.');return}setG(v=>({...v,cash:v.cash-c.price,car:c.name,mood:clamp(v.mood+6)}));log(`You bought a ${c.name} for ${money(c.price)}.`)}
 function reset(){localStorage.removeItem('abuja-real-life-save');setG(initial);log('Your new Abuja life has begun.');}
 const xpPct=Math.min(100,(g.xp%100));
 return <main className="shell"><header className="topbar"><div className="brand"><div className="brandMark">AR</div><div><strong>ABUJA REAL LIFE</strong><span>LIVE THE CITY. BUILD YOUR STORY.</span></div></div><div className="topStats"><span>DAY {g.day}</span><span>☀️ {time}</span><b>{money(g.cash)}</b></div></header>
 <div className="layout"><section className="world"><World look={g.look} district={g.district} setDistrict={travel} onMove={setMoving}/><div className="hud"><div><strong>📍 {g.district}, Abuja</strong><span>{moving?'Moving around the city':'Explore the city and build your life'}</span></div><div className="controls">WASD · Drag to look · Scroll to zoom</div></div></section>
 <aside className="side"><nav className="tabs">{[['home','⌂','Home'],['phone','▣','Phone'],['jobs','💼','Jobs'],['bank','₦','Bank'],['map','⌖','City'],['profile','◉','Me']].map(([k,i,l])=><button key={k} className={tab===k?'selected':''} onClick={()=>setTab(k as Tab)}><span>{i}</span>{l}</button>)}</nav>
 {tab==='home'&&<><Card><div className="profile"><div className="avatar">🧑🏾</div><div><b>{g.name}</b><div className="muted">{g.job} · Level {g.level}</div><div className="xp"><i style={{width:`${xpPct}%`}}/></div></div></div><div className="statGrid"><Stat label="ENERGY" value={g.energy}/><Stat label="MOOD" value={g.mood}/><Stat label="HEALTH" value={g.health}/><Stat label="HUNGER" value={g.hunger}/></div></Card><Card title="Daily life"><div className="actions"><button onClick={()=>work()}><b>💼 Work</b><small>Earn your salary</small></button><button onClick={eat}><b>🍲 Eat</b><small>Restore hunger</small></button><button onClick={rest}><b>🛌 Rest</b><small>Recover energy</small></button><button onClick={gym}><b>🏋🏾 Gym</b><small>Build fitness</small></button></div></Card><Card title="Missions"><div className="missionList">{g.missions.map((m,i)=><div key={m} className="mission"><span>◉</span><div>{m}<small>{i===0?'Reward: ₦5,000':i===1?'Reward: +20 mood':'Reward: +50 XP'}</small></div></div>)}</div></Card></>}
 {tab==='phone'&&<><Card title="📱 Your Phone"><div className="phoneGrid"><button onClick={()=>log('You checked your contacts. No new messages.')}>👥<small>Contacts</small></button><button onClick={()=>log('You posted a status. +2 mood.')}>📸<small>Status</small></button><button onClick={()=>log('No urgent notifications.')}>🔔<small>Alerts</small></button><button onClick={()=>log('You browsed Abuja events.')}>🎟️<small>Events</small></button></div></Card><Card title="Activity feed">{g.feed.map((f,i)=><div className="event" key={i}>{f}</div>)}</Card></>}
 {tab==='jobs'&&<Card title="💼 Jobs in Abuja"><p className="muted">Choose a career. Your current role is <b>{g.job}</b>.</p>{jobs.map(j=><div className="rowItem" key={j.name}><div><b>{j.name}</b><small>₦{j.pay.toLocaleString()} / shift · {j.xp} XP</small></div><button onClick={()=>{setG(v=>({...v,job:j.name}));work(j)}}>Work</button></div>)}</Card>}
 {tab==='bank'&&<><Card title="🏦 Bank"><div className="balance"><small>Total liquid wealth</small><strong>{money(g.cash+g.bank)}</strong><span>Cash {money(g.cash)} · Bank {money(g.bank)}</span></div><div className="bankActions"><button onClick={deposit}>Deposit ₦10k</button><button onClick={withdraw}>Withdraw ₦10k</button></div></Card><Card title="Property"><div className="rowItem"><div><b>{g.property}</b><small>Current home</small></div></div>{properties.map(p=><div className="rowItem" key={p.name}><div><b>{p.name}</b><small>{money(p.price)} · comfort +{p.comfort}</small></div><button onClick={()=>buyProperty(p)}>Buy</button></div>)}</Card><Card title="Vehicles"><div className="rowItem"><div><b>{g.car}</b><small>Current vehicle</small></div></div>{cars.map(c=><div className="rowItem" key={c.name}><div><b>{c.name}</b><small>{money(c.price)}</small></div><button onClick={()=>buyCar(c)}>Buy</button></div>)}</Card></>}
 {tab==='map'&&<Card title="🗺️ Explore Abuja"><p className="muted">Transport between districts, then explore on foot.</p><div className="districtList">{(['Wuse','Garki','Maitama','Jabi','Gwarinpa','Asokoro'] as District[]).map(d=><button className={g.district===d?'current':''} key={d} onClick={()=>travel(d)}><b>{d}</b><small>{d==='Jabi'?'Lake, nightlife & leisure':d==='Maitama'?'Luxury & embassies':d==='Wuse'?'Markets & business':d==='Garki'?'Offices & services':d==='Gwarinpa'?'Homes & local life':'Upscale residential'}</small></button>)}</div></Card>}
 {tab==='profile'&&<><Card title="👤 Character"><div className="profileLarge"><div className="avatar big">🧑🏾</div><div><h2>{g.name}</h2><p className="muted">Level {g.level} · {g.job}</p><p>Fitness {g.fitness}% · Health {g.health}%</p></div></div><div className="lookGrid"><label>Shirt<select value={g.look.shirt} onChange={e=>setG(v=>({...v,look:{...v.look,shirt:e.target.value}}))}><option value="#126c4b">Green</option><option value="#b43c35">Red</option><option value="#d18a22">Gold</option><option value="#3d5a80">Blue</option></select></label><label>Hair<select value={g.look.hair} onChange={e=>setG(v=>({...v,look:{...v.look,hair:e.target.value}}))}><option value="#151515">Black</option><option value="#4b2e1f">Brown</option><option value="#c5a46d">Gold</option></select></label></div></Card><Card title="Save & reset"><p className="muted">Your current game is saved in this browser automatically.</p><button className="danger" onClick={reset}>Start a new life</button></Card></>}
 <div className="notice" aria-live="polite">{notice}</div><div className="footerNote">Abuja Real Life · v1 foundation · Local save enabled · Vercel ready</div></aside></div></main>
}
function Card({title,children}:{title?:string;children:ReactNode}){return <section className="card">{title&&<div className="sectionTitle">{title}</div>}{children}</section>}
function Stat({label,value}:{label:string;value:number}){return <div className="stat"><small>{label}</small><b>{Math.round(value)}%</b><div className="bar"><i style={{width:`${value}%`}}/></div></div>}
