'use client';
import { useEffect,useState } from 'react';
import { BizManage,MyJobs,useBizJobs } from './BizManage';
const post=async(u:string,b:any)=>{const r=await fetch(u,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)});return {ok:r.ok,d:await r.json().catch(()=>({}))}};
const naira=(n:number)=>'₦'+Math.round(n).toLocaleString('en-NG');
export default function CityLifePanel(){
 const [me,setMe]=useState(''),[snap,setSnap]=useState<any>(null),[biz,setBiz]=useState<any>(null),[career,setCareer]=useState<any[]>([]),[rep,setRep]=useState<any>(null),[driver,setDriver]=useState<any>(null),[friends,setFriends]=useState<any[]>([]),[busy,setBusy]=useState(''),[msg,setMsg]=useState(''),[friendName,setFriendName]=useState(''),[gift,setGift]=useState(''),[menu,setMenu]=useState<Record<string,string>>({}),[fare,setFare]=useState({baseFare:1500,perKm:450});
 const {d:jobsData,load:loadJobs}=useBizJobs();
 const load=async()=>{const [m,a,b,c,d,e,f]=await Promise.all([fetch('/api/auth/me').then(r=>r.json()),fetch('/api/city-life').then(r=>r.json()),fetch('/api/businesses').then(r=>r.json()),fetch('/api/career').then(r=>r.json()),fetch('/api/reputation').then(r=>r.json()),fetch('/api/driver').then(r=>r.json()),fetch('/api/relationship').then(r=>r.json())]);setMe(m?.user?.username||m?.username||'');setSnap(a);setBiz(b);setCareer(c.careers||[]);setRep(d.reputation);setDriver(e.driver);setFriends(f.friends||[])};
 useEffect(()=>{load();const i=setInterval(load,15000);return()=>clearInterval(i)},[]);
 const act=async(action:string,businessId?:string,extra:any={})=>{setBusy(action+(businessId||''));const r=await post('/api/businesses',{action,businessId,...extra});setMsg(r.ok?`Done. ${r.d?.business?.name||''}`:r.d?.error||'Action failed');setBusy('');if(r.ok)load()};
 const respond=async(eventId:string)=>{const r=await post('/api/city-events',{eventId});setMsg(r.ok?`Emergency response complete: +${naira(r.d.reward||0)}`:r.d?.error||'Event ended');if(r.ok)load()};
 const social=async(body:any)=>{const r=await post('/api/relationship',body);setMsg(r.ok?'Request sent.':r.d?.error||'Could not complete');if(r.ok){setFriendName('');load()}};
 const saveFare=async()=>{const r=await post('/api/driver',{action:'settings',...fare});setDriver(r.d.driver);setMsg(r.ok?'Driver fares saved.':r.d?.error||'Could not save fares')};
 if(!snap)return <div className="cityLife"><h3>🌆 Living Abuja</h3><p>Loading the city simulation…</p></div>;
 const p=snap.districts.find((d:any)=>d.playerDistrict), wealth=snap.wealth;
 return <div className="cityLife"><h3>🌆 Living Abuja</h3><div className="lifeHero"><b>{snap.weather.e} {snap.weather.label}</b><span>{snap.clock.clock} · {snap.clock.weekday} · {snap.clock.season.label}</span><small>{p?.name} · {p?.mood}</small></div>
  <section><h4>💰 Wealth progression</h4><div className="wealth"><b>{wealth?.e} {wealth?.label}</b><span>{naira(wealth?.cash||0)}</span><small>{wealth?.next ? `Next: ${wealth.next.label} at ${naira(wealth.next.at)}` : 'Top wealth tier reached.'}</small></div></section>
  <section><h4>🚨 Live city events</h4>{snap.events.map((e:any)=><div className="lifeCard" key={e.id}><b>{e.title}</b><small>{e.district} · {e.description}</small><button onClick={()=>respond(e.id)}>Respond</button></div>)}</section>
  <section><h4>🏙️ District pulse</h4>{snap.districts.slice(0,10).map((d:any)=><div className="districtRow" key={d.name}><span><b>{d.name}</b><small>{d.mood}</small></span><em>{d.npcs} NPCs · {d.traffic}% traffic · demand {d.demand}%</em></div>)}</section>
  <section><h4>👥 Friends & social</h4>{friends.map((f:any)=>{const other=f.aName===me?f.bName:f.aName;return <div className="lifeCard" key={f.id}><b>{other}</b><small>{f.status}</small><button onClick={async()=>{await post('/api/relationship',{action:'gift',to:other,amount:Number(gift)||1000});setMsg(`Gift sent to ${other}.`);load()}}>Gift ₦{gift||'1,000'}</button><button onClick={()=>post('/api/relationship',{action:'unfriend',with:other}).then(load)}>Unfriend</button></div>})}<div className="socialForm"><input placeholder="Player username" value={friendName} onChange={e=>setFriendName(e.target.value)}/><button disabled={!friendName} onClick={()=>social({action:'propose',to:friendName,status:'friends'})}>Add friend</button><input placeholder="Gift amount" inputMode="numeric" value={gift} onChange={e=>setGift(e.target.value)}/></div></section>
  <section><h4>💼 Career progression</h4>{career.length?career.map(c=><div className="lifeCard" key={c.id}><b>{c.title} · Rank {c.rank}</b><small>{c.profession} · {c.xp} XP · {c.completed} completed · +{naira(c.salaryBonus)}/shift</small></div>):<p className="muted">Complete shifts to build a career ladder.</p>}<button onClick={async()=>{const r=await post('/api/career',{action:'complete',xp:20});setMsg(r.ok?'Career XP awarded.':r.d.error);load()}}>Complete career activity</button></section>
  <section><h4>💼 My jobs</h4><MyJobs jobs={jobsData?.jobs||[]} say={setMsg} reload={()=>{loadJobs();load()}}/></section>
  <section><h4>🏢 Businesses</h4>{biz?.mine?.length?biz.mine.map((b:any)=><div className="lifeCard" key={b.id}><b>{b.name} · L{b.level}</b><small>{b.type} · {b.district} · {b.staff} staff · reputation {b.reputation} · profit {naira(b.balance)}</small><div className="lifeBtns"><button disabled={!!busy} onClick={()=>act('collect',b.businessId)}>Collect</button><button disabled={!!busy} onClick={()=>act('upgrade',b.businessId)}>Upgrade</button></div><BizManage businessId={b.businessId} pricing={b.pricing} owner={jobsData?.owner.find(o=>o.businessId===b.businessId)} say={setMsg} reload={()=>{load();loadJobs()}}/>{(b.type==='Restaurant'||b.type==='Hotel')&&<div className="menuEdit"><input placeholder="Menu item" id={`mi-${b.id}`} /><input placeholder="₦ price" id={`mp-${b.id}`} inputMode="numeric"/><button onClick={()=>{const n=(document.getElementById(`mi-${b.id}`) as HTMLInputElement)?.value;const pr=Number((document.getElementById(`mp-${b.id}`) as HTMLInputElement)?.value)||3000;const current=Array.isArray(b.menu)?b.menu:[];act('setmenu',b.businessId,{menu:[...current,{name:n,price:pr}]})}}>Add menu item</button></div>}</div>):<p className="muted">Buy a business below and build a real operating empire.</p>}{biz?.available?.slice(0,10).map((b:any)=><div className="lifeCard" key={b.id}><b>{b.name}</b><small>{b.type} · {b.district} · {naira(b.price)}</small><button disabled={!!busy} onClick={()=>act('buy',b.id)}>Buy business</button></div>)}</section>
  <section><h4>🚕 Driver mode</h4><div className="lifeCard"><b>{driver?.active?'Online for passengers':'Offline'}</b><small>Base fare + per-km fare are used for player taxi/bike jobs.</small><div className="socialForm"><input value={fare.baseFare} onChange={e=>setFare({...fare,baseFare:Number(e.target.value)})}/><input value={fare.perKm} onChange={e=>setFare({...fare,perKm:Number(e.target.value)})}/></div><button onClick={()=>post('/api/driver',{action:'toggle'}).then(()=>load())}>{driver?.active?'Go offline':'Go online'}</button><button onClick={saveFare}>Save fares</button></div></section>
  <section><h4>⭐ My reputation</h4><div className="repGrid"><b>{rep?.score??50}<small>Overall</small></b><b>{rep?.trust??50}<small>Trust</small></b><b>{rep?.social??50}<small>Social</small></b><b>{rep?.crime??0}<small>Crime</small></b></div></section>
  {msg&&<div className="lifeMsg">{msg}</div>}
  <style jsx>{`.cityLife{color:#fff}.cityLife h3{margin:0 0 10px}.lifeHero{display:grid;gap:3px;background:linear-gradient(135deg,#123c2d,#0c1915);border:1px solid #ffffff18;border-radius:14px;padding:12px}.lifeHero span,.lifeHero small,.muted{color:#91a99d;font-size:11px}.cityLife section{margin-top:13px}.cityLife h4{margin:0 0 7px;font-size:12px}.lifeCard{background:#10221b;border:1px solid #ffffff12;border-radius:10px;padding:9px;margin:5px 0}.lifeCard b,.lifeCard small{display:block}.lifeCard small{color:#91a99d;font-size:10px;margin-top:3px}.lifeCard button,.cityLife section>button{margin-top:7px;margin-right:5px;background:#d99a42;color:#171008;border:0;border-radius:8px;padding:7px 9px;font-weight:800;font-size:11px}.lifeBtns{display:flex;gap:5px;flex-wrap:wrap;margin-top:5px}.lifeBtns select,.socialForm input{background:#0a1511;color:#fff;border:1px solid #2a4337;border-radius:7px;padding:6px;font-size:10px}.districtRow{display:flex;justify-content:space-between;align-items:center;background:#0e1c17;border-bottom:1px solid #ffffff0b;padding:7px}.districtRow span small{display:block;color:#91a99d;font-size:9px}.districtRow em{font-size:9px;color:#8ea79a;font-style:normal}.repGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:5px}.repGrid b{background:#10221b;border-radius:9px;padding:8px;text-align:center}.repGrid small{display:block;color:#91a99d;font-size:8px;margin-top:2px}.wealth{display:grid;gap:4px;background:#10221b;border:1px solid #ffffff12;border-radius:10px;padding:10px}.wealth span{color:#f3c56f;font-weight:800}.wealth small{color:#91a99d}.lifeMsg{position:sticky;bottom:4px;background:#d99a42;color:#171008;padding:8px;border-radius:9px;font-weight:800;font-size:11px}.socialForm{display:flex;gap:5px;flex-wrap:wrap;margin-top:7px}.socialForm input{flex:1;min-width:90px}.menuEdit{display:flex;gap:4px;flex-wrap:wrap;margin-top:7px}.menuEdit input{background:#0a1511;color:#fff;border:1px solid #2a4337;border-radius:7px;padding:6px;min-width:70px}`}</style>
 </div>
}
