'use client';
import { useEffect,useState } from 'react';
const post=async(u:string,b:any)=>{const r=await fetch(u,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)});return {ok:r.ok,d:await r.json().catch(()=>({}))}};
const naira=(n:number)=>'₦'+Math.round(n).toLocaleString('en-NG');
type Snap=any;
export default function CityLifePanel(){
 const [snap,setSnap]=useState<Snap|null>(null),[biz,setBiz]=useState<any>(null),[career,setCareer]=useState<any[]>([]),[rep,setRep]=useState<any>(null),[busy,setBusy]=useState(''),[msg,setMsg]=useState('');
 const load=async()=>{const [a,b,c,d]=await Promise.all([fetch('/api/city-life').then(r=>r.json()),fetch('/api/businesses').then(r=>r.json()),fetch('/api/career').then(r=>r.json()),fetch('/api/reputation').then(r=>r.json())]);setSnap(a);setBiz(b);setCareer(c.careers||[]);setRep(d.reputation)};
 useEffect(()=>{load();const i=setInterval(load,15000);return()=>clearInterval(i)},[]);
 const respond=async(eventId:string)=>{const r=await post('/api/city-events',{eventId});setMsg(r.ok?`Emergency response complete: +₦${Number(r.d.reward||0).toLocaleString()}`:r.d?.error||'Event ended');if(r.ok)load()};
 const act=async(action:string,businessId?:string)=>{setBusy(action+(businessId||''));const r=await post('/api/businesses',{action,businessId});setMsg(r.ok?`Done. ${r.d?.business?.name||''}`:r.d?.error||'Action failed');setBusy('');if(r.ok)load()};
 if(!snap)return <div className="cityLife"><h3>🌆 Living Abuja</h3><p>Loading the city simulation…</p></div>;
 const p=snap.districts.find((d:any)=>d.playerDistrict);
 return <div className="cityLife"><h3>🌆 Living Abuja</h3><div className="lifeHero"><b>{snap.weather.e} {snap.weather.label}</b><span>{snap.clock.clock} · {snap.clock.weekday} · {snap.clock.season.label}</span><small>{p?.name} · {p?.mood}</small></div>
  <section><h4>🚨 Live city events</h4>{snap.events.map((e:any)=><div className="lifeCard" key={e.id}><b>{e.title}</b><small>{e.district} · {e.description}</small><button onClick={()=>respond(e.id)}>Respond</button></div>)}</section>
  <section><h4>🏙️ District pulse</h4>{snap.districts.slice(0,8).map((d:any)=><div className="districtRow" key={d.name}><span><b>{d.name}</b><small>{d.mood}</small></span><em>{d.npcs} NPCs · {d.traffic}% traffic</em></div>)}</section>
  <section><h4>👥 People are living</h4><p className="muted">{snap.npcCount} ambient citizens are simulated across homes, workplaces and social areas. Sample: {snap.npcSample.slice(0,4).map((n:any)=>`${n.name} (${n.activity})`).join(' · ')}.</p></section>
  <section><h4>⭐ My reputation</h4><div className="repGrid"><b>{rep?.score??50}<small>Overall</small></b><b>{rep?.trust??50}<small>Trust</small></b><b>{rep?.social??50}<small>Social</small></b><b>{rep?.crime??0}<small>Crime</small></b></div></section>
  <section><h4>💼 Career progression</h4>{career.length?career.map(c=><div className="lifeCard" key={c.id}><b>{c.title} · Rank {c.rank}</b><small>{c.profession} · {c.xp} XP · {c.completed} completed · +{naira(c.salaryBonus)}/shift</small></div>):<p className="muted">Complete shifts to build a career ladder.</p>}<button onClick={async()=>{const r=await post('/api/career',{action:'complete',xp:20});setMsg(r.ok?'Career XP awarded from a completed activity.':r.d.error);load()}}>Complete career activity</button></section>
  <section><h4>🏢 My businesses</h4>{biz?.mine?.length?biz.mine.map((b:any)=><div className="lifeCard" key={b.id}><b>{b.name} · L{b.level}</b><small>{b.type} · {b.district} · {b.staff} staff · reputation {b.reputation}</small><div className="lifeBtns"><button disabled={!!busy} onClick={()=>act('collect',b.businessId)}>Collect</button><button disabled={!!busy} onClick={()=>act('upgrade',b.businessId)}>Upgrade</button><button disabled={busy==='hire'+b.businessId} onClick={()=>act('hire',b.businessId)}>Hire staff</button></div></div>):<p className="muted">Buy a business below and build a real operating empire.</p>}
  {biz?.available?.slice(0,10).map((b:any)=><div className="lifeCard" key={b.id}><b>{b.name}</b><small>{b.type} · {b.district} · {naira(b.price)}</small><button disabled={!!busy} onClick={()=>act('buy',b.id)}>Buy business</button></div>)}</section>
  {msg&&<div className="lifeMsg">{msg}</div>}
  <style jsx>{`.cityLife{color:#fff}.cityLife h3{margin:0 0 10px}.lifeHero{display:grid;gap:3px;background:linear-gradient(135deg,#123c2d,#0c1915);border:1px solid #ffffff18;border-radius:14px;padding:12px}.lifeHero span,.lifeHero small,.muted{color:#91a99d;font-size:11px}.cityLife section{margin-top:13px}.cityLife h4{margin:0 0 7px;font-size:12px}.lifeCard{background:#10221b;border:1px solid #ffffff12;border-radius:10px;padding:9px;margin:5px 0}.lifeCard b,.lifeCard small{display:block}.lifeCard small{color:#91a99d;font-size:10px;margin-top:3px}.lifeCard button,.cityLife section>button{margin-top:7px;background:#d99a42;color:#171008;border:0;border-radius:8px;padding:7px 9px;font-weight:800;font-size:11px}.lifeBtns{display:flex;gap:6px}.districtRow{display:flex;justify-content:space-between;align-items:center;background:#0e1c17;border-bottom:1px solid #ffffff0b;padding:7px}.districtRow span small{display:block;color:#91a99d;font-size:9px}.districtRow em{font-size:9px;color:#8ea79a;font-style:normal}.repGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:5px}.repGrid b{background:#10221b;border-radius:9px;padding:8px;text-align:center}.repGrid small{display:block;color:#91a99d;font-size:8px;margin-top:2px}.lifeMsg{position:sticky;bottom:4px;background:#d99a42;color:#171008;padding:8px;border-radius:9px;font-weight:800;font-size:11px}`}</style>
 </div>
}
