'use client';
import { Canvas, useFrame } from '@react-three/fiber';
import { Html, OrbitControls, RoundedBox, Text } from '@react-three/drei';
import { useEffect, useMemo, useRef, useState } from 'react';
import * as THREE from 'three';
import Human from './Human';
import { CITY } from '../lib/cityData';
import { makeTraffic, tickTraffic, type TrafficCar } from '../lib/citySim';
import type { Look } from '../lib/characterModels';

function Building({b}:{b:any}){return <group position={[b.x,b.h/2,b.z]}><RoundedBox args={[b.w,b.h,b.d]} radius={.18} smoothness={2} castShadow receiveShadow><meshStandardMaterial color={b.color}/></RoundedBox>{b.business&&<Text position={[0,b.h/2+.3,b.d/2+.02]} fontSize={.22} color="#fff" anchorX="center" anchorY="middle">{b.business.name}</Text>}{Array.from({length:Math.max(1,Math.floor(b.h/1.8))}).map((_,r)=>Array.from({length:3}).map((__,c)=><mesh key={r+'-'+c} position={[-b.w*.25+c*b.w*.25,.45+r*1.15,b.d/2+.025]}><planeGeometry args={[.32,.42]}/><meshStandardMaterial color="#a8d5ed" emissive="#7bb8dc" emissiveIntensity={.18}/></mesh>))}</group>}
function Road({r}:{r:any}){return <mesh position={[r.x,.015,r.z]} rotation={[-Math.PI/2,0,0]} receiveShadow><planeGeometry args={[r.w,r.d]}/><meshStandardMaterial color={r.major?'#292d33':'#363b42'}/></mesh>}
function Car({c}:{c:TrafficCar}){return <group position={[c.x,.25,c.z]} rotation={[0,c.rot,0]}><RoundedBox args={[1.45,.35,.72]} radius={.1} smoothness={2}><meshStandardMaterial color={c.color}/></RoundedBox><mesh position={[0,.22,0]}><boxGeometry args={[.7,.25,.58]}/><meshStandardMaterial color="#9fc3d4"/></mesh></group>}
function Train({x,z}:{x:number;z:number}){return <group position={[x,.75,z]}><RoundedBox args={[5,.8,1.2]} radius={.12} smoothness={2}><meshStandardMaterial color="#d99a42"/></RoundedBox>{[-1.6,0,1.6].map(v=><mesh key={v} position={[v,.12,.62]}><boxGeometry args={[1.05,.38,.03]}/><meshStandardMaterial color="#bfe1f0"/></mesh>)}</group>}
function Airport({x,z}:{x:number;z:number}){return <group position={[x,0,z]}><mesh rotation={[-Math.PI/2,0,0]} position={[0,.02,0]}><planeGeometry args={[22,7]}/><meshStandardMaterial color="#33383e"/></mesh><Text position={[0,.1,0]} rotation={[-Math.PI/2,0,0]} fontSize={.6} color="#fff" anchorX="center">RUNWAY</Text><RoundedBox args={[9,1.5,5]} position={[0,.75,-7]} radius={.15}><meshStandardMaterial color="#7b8791"/></RoundedBox><Text position={[0,1.65,-4.4]} fontSize={.45} color="#fff" anchorX="center">Nnamdi Azikiwe Airport</Text></group>}
function Scene({look,joy,setNear}:{look:Look;joy:React.MutableRefObject<{x:number;y:number}>;setNear:(b:any)=>void}){const pos=useRef({x:0,z:8,r:Math.PI}),target=useRef({x:0,z:8}),group=useRef<THREE.Group>(null!);const cars=useMemo(()=>makeTraffic(),[]),train=useRef(-55);const [near,setN]=useState<any>(null);
useFrame((_,dt)=>{const j=joy.current;if(Math.hypot(j.x,j.y)>.05){target.current.x=THREE.MathUtils.clamp(target.current.x+j.x*dt*7,-58,58);target.current.z=THREE.MathUtils.clamp(target.current.z+j.y*dt*7,-58,58);pos.current.r=Math.atan2(j.x,j.y)}const dx=target.current.x-pos.current.x,dz=target.current.z-pos.current.z,d=Math.hypot(dx,dz);if(d>.05){const s=Math.min(d,dt*7);pos.current.x+=dx/d*s;pos.current.z+=dz/d*s}group.current.position.set(pos.current.x,0,pos.current.z);group.current.rotation.y=pos.current.r;tickTraffic(cars,dt);train.current+=dt*4;if(train.current>65)train.current=-55;const b=CITY.businesses.reduce((a,v)=>!a||Math.hypot(v.x-pos.current.x,v.z-pos.current.z)<Math.hypot(a.x-pos.current.x,a.z-pos.current.z)?v:a,null as any);if(b&&Math.hypot(b.x-pos.current.x,b.z-pos.current.z)<5){setN(b);setNear(b)}else{setN(null);setNear(null)}});
useEffect(()=>{const f=(e:KeyboardEvent)=>{const k=e.key.toLowerCase();if(k==='w'||k==='arrowup')joy.current.y=-1;if(k==='s'||k==='arrowdown')joy.current.y=1;if(k==='a'||k==='arrowleft')joy.current.x=-1;if(k==='d'||k==='arrowright')joy.current.x=1};const u=()=>{joy.current={x:0,y:0}};window.addEventListener('keydown',f);window.addEventListener('keyup',u);return()=>{window.removeEventListener('keydown',f);window.removeEventListener('keyup',u)}},[joy]);
return <><hemisphereLight args={['#dff0ff','#536b4d',1.8]}/><directionalLight position={[30,45,20]} intensity={3} castShadow shadow-mapSize={[1024,1024]}/><mesh rotation={[-Math.PI/2,0,0]} receiveShadow><planeGeometry args={[130,130]}/><meshStandardMaterial color="#52734d"/></mesh>{CITY.roads.map(r=><Road key={r.id} r={r}/>)}{CITY.buildings.map(b=><Building key={b.id} b={b}/>)}{cars.map((c,i)=><Car key={i} c={c}/>)}{CITY.rail.map((p,i)=><mesh key={i} position={[p.x,.15,p.z]}><boxGeometry args={[7,.12,.16]}/><meshStandardMaterial color="#555"/></mesh>)}<Train x={train.current} z={13}/><Airport x={54} z={-5}/><group ref={group}><Human look={look} getState={()=>'walk'}/><Html position={[0,2.8,0]} center><div className="cityNameTag">{look.name}</div></Html></group>{near&&<Html position={[near.x,4,near.z]} center><div className="cityBizTag">{near.name}<br/><small>{near.type}</small></div></Html>}<OrbitControls enablePan={false} minDistance={7} maxDistance={28} maxPolarAngle={Math.PI/2.1}/></>}
export default function CityWorld({look,onNear}:{look:Look;onNear:(b:any)=>void}){const joy=useRef({x:0,y:0});return <div className="cityWorld"><Canvas shadows dpr={[1,1.5]} camera={{position:[8,10,14],fov:46}}><Scene look={look} joy={joy} setNear={onNear}/></Canvas><div className="cityTouch"><div className="cityStick" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();joy.current={x:THREE.MathUtils.clamp((e.clientX-(r.left+r.width/2))/(r.width/2),-1,1),y:THREE.MathUtils.clamp((e.clientY-(r.top+r.height/2))/(r.height/2),-1,1)}}} onPointerUp={()=>joy.current={x:0,y:0}} onPointerCancel={()=>joy.current={x:0,y:0}}><i/></div></div>}
