import { NextResponse } from 'next/server';
import type { PlayerBusiness } from '@prisma/client';
import { prisma } from '../../../lib/prisma';
import { currentUser, err } from '../../../lib/auth';
import { CITY } from '../../../lib/cityData';
import { activeCityEvents, districtProfile } from '../../../lib/livingCity';
import { ACCRUE_CAP_MINS, MAX_SHIFT_MS, cleanMarkup, cleanPrices, maxStaff, priceFactor, priceIndex, priceOf, sellable, settle } from '../../../lib/bizEconomy';
const ROLE_COST:Record<string,number>={manager:400000,chef:250000,waiter:120000,cashier:100000,security:110000,staff:150000};
const distMul=(d:string)=>0.7+districtProfile(d).wealth/160; // Maitama costs more, Kubwa less
const PRICE:Record<string,number>={Restaurant:85000000,Hotel:250000000,Supermarket:65000000,Salon:18000000,Barber:12000000,Gym:30000000,Mechanic:45000000,'Car Dealer':150000000,Nightclub:95000000,Market:55000000,Pharmacy:30000000,Cinema:180000000,'Tech Company':120000000,'Estate Agency':45000000,Logistics:80000000};
export const dynamic='force-dynamic';
type Biz=PlayerBusiness;
const cfg=(b:{markup:number;prices:unknown})=>({markup:b.markup,prices:b.prices});
/* Idle sales since the last settlement: crowd size depends on how our prices compare with the other player-run shops of the same type in the same district,
   and on staff on shift. The net (sales - supplier cost - overhead) goes into the till, which is where wages are paid from. */
async function accrue(b:Biz,events:Awaited<ReturnType<typeof activeCityEvents>>,now:number){
 const mins=Math.max(0,Math.min(ACCRUE_CAP_MINS,Math.floor((now-b.settledAt.getTime())/60000))); if(!mins)return b;
 const [rivals,onShift]=await Promise.all([prisma.playerBusiness.findMany({where:{type:b.type,district:b.district,NOT:{id:b.id}},select:{type:true,markup:true,prices:true}}),prisma.businessEmployee.count({where:{businessId:b.businessId,status:'ACTIVE',clockedInAt:{gt:new Date(now-MAX_SHIFT_MS)}}})]);
 const mine=priceIndex(b.type,cfg(b)),factor=priceFactor(mine,rivals.map(r=>priceIndex(r.type,cfg(r))));
 const bonus=events.filter(e=>e.district===b.district||e.kind==='traffic').reduce((n,e)=>n+e.intensity,0);
 const r=settle(mins,{level:b.level,staff:b.staff,rep:b.reputation,eventBonus:bonus,index:mine,factor,onShift});
 const done=await prisma.playerBusiness.updateMany({where:{id:b.id,settledAt:b.settledAt},data:{settledAt:new Date(b.settledAt.getTime()+mins*60000),balance:{increment:r.net},revenue:{increment:r.revenue},expenses:{increment:r.cogs+r.overhead}}});
 return done.count?(await prisma.playerBusiness.findUnique({where:{id:b.id}}))||b:b;
}
async function pricing(b:Biz){
 const [rivals,crew]=await Promise.all([prisma.playerBusiness.findMany({where:{type:b.type,district:b.district,NOT:{id:b.id}},select:{type:true,markup:true,prices:true}}),prisma.businessEmployee.count({where:{businessId:b.businessId,status:{in:['OFFERED','ACTIVE']}}})]);
 const mine=priceIndex(b.type,cfg(b)),ri=rivals.map(r=>priceIndex(r.type,cfg(r)));
 return {markup:b.markup,index:Math.round(mine*100)/100,rivals:rivals.length,market:Math.round((1+ri.reduce((a,c)=>a+c,0))/(1+ri.length)*100)/100,customers:Math.round(priceFactor(mine,ri)*100),capacity:maxStaff(b.level),crew,services:sellable(b.type).filter(s=>s.service).map(s=>({id:s.id,name:s.name,base:s.base,price:priceOf(b.type,cfg(b),s.id)})),sells:sellable(b.type).length};
}
export async function GET(){const u=await currentUser();if(!u)return err('Not signed in.',401);const events=await activeCityEvents(); const mine0=await prisma.playerBusiness.findMany({where:{userId:u.id},orderBy:{createdAt:'desc'}}); const now=Date.now(); const settled=await Promise.all(mine0.map(b=>accrue(b,events,now))); const mine=await Promise.all(settled.map(async b=>({...b,pricing:await pricing(b)})));const owned=new Set((await prisma.playerBusiness.findMany({select:{businessId:true}})).map(x=>x.businessId));const available=CITY.businesses.filter(b=>PRICE[b.type]&&!owned.has(b.id)).map(b=>({...b,price:Math.round(PRICE[b.type]*distMul(b.district)/1000)*1000}));return NextResponse.json({mine,available});}
export async function POST(req:Request){const u=await currentUser();if(!u)return err('Not signed in.',401);const body=await req.json().catch(()=>({}));const {action,businessId,role:roleIn,menu:menuIn}=body;const b=CITY.businesses.find(x=>x.id===String(businessId));if(!b)return err('Business not found.',404);const price=Math.round((PRICE[b.type]||0)*distMul(b.district)/1000)*1000;const save=await prisma.save.findUnique({where:{userId:u.id}});if(!save)return err('Create your character first.',409);if(action==='buy'){if(!price)return err('This business is not purchasable yet.',400);if(save.cash<price)return err('You cannot afford this business.',402);const exists=await prisma.playerBusiness.findUnique({where:{businessId:b.id}});if(exists)return err('This business already has an owner.',409);const row=await prisma.$transaction(async tx=>{await tx.save.update({where:{userId:u.id},data:{cash:{decrement:price}}});await tx.transaction.create({data:{userId:u.id,type:'SPEND',amount:-price,description:`business:${b.name}`}});return tx.playerBusiness.create({data:{userId:u.id,businessId:b.id,name:b.name,type:b.type,district:b.district,menu:b.type==='Restaurant'?['Jollof Rice','Grilled Chicken','Pepper Soup']:undefined}})});return NextResponse.json({ok:true,business:row,cash:save.cash-price});}
if(action==='collect'){const row=await prisma.playerBusiness.findFirst({where:{userId:u.id,businessId:b.id}});if(!row)return err('You do not own this business.',403);const amount=row.balance;if(amount<=0)return err('No business profit is ready to collect.',409);const collected=await prisma.$transaction(async tx=>{await tx.playerBusiness.update({where:{id:row.id},data:{balance:0}});await tx.save.update({where:{userId:u.id},data:{cash:{increment:amount}}});await tx.transaction.create({data:{userId:u.id,type:'EARN',amount,description:`business-profit:${b.name}`}});return amount});return NextResponse.json({ok:true,profit:collected,cash:save.cash+collected});}
if(action==='upgrade'){const row=await prisma.playerBusiness.findFirst({where:{userId:u.id,businessId:b.id}});if(!row)return err('You do not own this business.',403);const cost=Math.round(price*(.18+row.level*.07));if(save.cash<cost)return err(`Upgrade costs ₦${cost.toLocaleString()}.`,402);const upgraded=await prisma.$transaction(async tx=>{await tx.save.update({where:{userId:u.id},data:{cash:{decrement:cost}}});await tx.transaction.create({data:{userId:u.id,type:'SPEND',amount:-cost,description:`business-upgrade:${b.name}:L${row.level+1}`}});return tx.playerBusiness.update({where:{id:row.id},data:{level:{increment:1},staff:{increment:2},reputation:{increment:4}}})});return NextResponse.json({ok:true,business:upgraded,cash:save.cash-cost});}
if(action==='setmenu'){const row=await prisma.playerBusiness.findFirst({where:{userId:u.id,businessId:b.id}});if(!row)return err('You do not own this business.',403);if(!Array.isArray(menuIn)||!menuIn.length||menuIn.length>20)return err('Menu needs 1-20 items.',400);const clean=menuIn.map((m:any)=>typeof m==='string'?{name:m.slice(0,40),price:3000}:{name:String(m?.name||'').slice(0,40),price:Math.max(100,Math.min(500000,Math.round(Number(m?.price)||0)))}).filter((m:{name:string})=>m.name);if(!clean.length)return err('Invalid menu.',400);const upd=await prisma.playerBusiness.update({where:{id:row.id},data:{menu:clean}});return NextResponse.json({ok:true,business:upd});}
if(action==='setprices'){const row=await prisma.playerBusiness.findFirst({where:{userId:u.id,businessId:b.id}});if(!row)return err('You do not own this business.',403);const markup=cleanMarkup(body.markup??row.markup);const kept=(row.prices&&typeof row.prices==='object'?row.prices:{}) as Record<string,number>;const prices=cleanPrices(row.type,body.prices?{...(body.markup===undefined?kept:{}),...body.prices}:body.markup===undefined?kept:{}); /* a new price level resets old per-item prices unless some are sent with it */const upd=await prisma.playerBusiness.update({where:{id:row.id},data:{markup,prices}});return NextResponse.json({ok:true,business:{...upd,pricing:await pricing(upd)}});}
if(action==='hire'){const row=await prisma.playerBusiness.findFirst({where:{userId:u.id,businessId:b.id}});if(!row)return err('You do not own this business.',403);const role=ROLE_COST[String(roleIn)]?String(roleIn):'staff';const cost=ROLE_COST[role]; if(save.cash<cost)return err(`Hiring a ${role} costs ₦${cost.toLocaleString()}.`,402);const hired=await prisma.$transaction(async tx=>{await tx.save.update({where:{userId:u.id},data:{cash:{decrement:cost}}});return tx.playerBusiness.update({where:{id:row.id},data:{staff:{increment:1},expenses:{increment:cost}}})});return NextResponse.json({ok:true,business:hired,cash:save.cash-cost});}
return err('Unknown action.',400);}
