import { NextResponse } from 'next/server';
import { prisma } from '../../../lib/prisma';
import { currentUser, err } from '../../../lib/auth';
import { CITY } from '../../../lib/cityData';
import { activeCityEvents } from '../../../lib/livingCity';
const PRICE:Record<string,number>={Restaurant:85000000,Hotel:250000000,Supermarket:65000000,Salon:18000000,Barber:12000000,Gym:30000000,Mechanic:45000000,'Car Dealer':150000000,Nightclub:95000000,Market:55000000,Pharmacy:30000000,Cinema:180000000,'Tech Company':120000000,'Estate Agency':45000000,Logistics:80000000};
export const dynamic='force-dynamic';
export async function GET(){const u=await currentUser();if(!u)return err('Not signed in.',401);const events=await activeCityEvents(); const mine0=await prisma.playerBusiness.findMany({where:{userId:u.id},orderBy:{createdAt:'desc'}}); const now=Date.now(); const mine=await Promise.all(mine0.map(async b=>{const mins=Math.max(0,Math.min(60,Math.floor((now-b.updatedAt.getTime())/60000))); if(!mins)return b; const bonus=events.filter(e=>e.district===b.district||e.kind==='traffic').reduce((n,e)=>n+e.intensity,0); const rev=Math.round(mins*(3500+b.level*1800+bonus*1200)); const exp=Math.round(mins*(900+b.staff*220)); return prisma.playerBusiness.update({where:{id:b.id},data:{revenue:{increment:rev},expenses:{increment:exp}}});}));const owned=new Set((await prisma.playerBusiness.findMany({select:{businessId:true}})).map(x=>x.businessId));const available=CITY.businesses.filter(b=>PRICE[b.type]&&!owned.has(b.id)).map(b=>({...b,price:PRICE[b.type]}));return NextResponse.json({mine,available});}
export async function POST(req:Request){const u=await currentUser();if(!u)return err('Not signed in.',401);const {action,businessId}=await req.json().catch(()=>({}));const b=CITY.businesses.find(x=>x.id===String(businessId));if(!b)return err('Business not found.',404);const price=PRICE[b.type]||0;const save=await prisma.save.findUnique({where:{userId:u.id}});if(!save)return err('Create your character first.',409);if(action==='buy'){if(!price)return err('This business is not purchasable yet.',400);if(save.cash<price)return err('You cannot afford this business.',402);const exists=await prisma.playerBusiness.findUnique({where:{businessId:b.id}});if(exists)return err('This business already has an owner.',409);const row=await prisma.$transaction(async tx=>{await tx.save.update({where:{userId:u.id},data:{cash:{decrement:price}}});await tx.transaction.create({data:{userId:u.id,type:'SPEND',amount:-price,description:`business:${b.name}`}});return tx.playerBusiness.create({data:{userId:u.id,businessId:b.id,name:b.name,type:b.type,district:b.district,menu:b.type==='Restaurant'?['Jollof Rice','Grilled Chicken','Pepper Soup']:undefined}})});return NextResponse.json({ok:true,business:row,cash:save.cash-price});}
if(action==='collect'){const row=await prisma.playerBusiness.findFirst({where:{userId:u.id,businessId:b.id}});if(!row)return err('You do not own this business.',403);const amount=row.balance;if(amount<=0)return err('No business profit is ready to collect.',409);const collected=await prisma.$transaction(async tx=>{await tx.playerBusiness.update({where:{id:row.id},data:{balance:0}});await tx.save.update({where:{userId:u.id},data:{cash:{increment:amount}}});await tx.transaction.create({data:{userId:u.id,type:'EARN',amount,description:`business-profit:${b.name}`}});return amount});return NextResponse.json({ok:true,profit:collected,cash:save.cash+collected});}
if(action==='upgrade'){const row=await prisma.playerBusiness.findFirst({where:{userId:u.id,businessId:b.id}});if(!row)return err('You do not own this business.',403);const cost=Math.round(price*(.18+row.level*.07));if(save.cash<cost)return err(`Upgrade costs ₦${cost.toLocaleString()}.`,402);const upgraded=await prisma.$transaction(async tx=>{await tx.save.update({where:{userId:u.id},data:{cash:{decrement:cost}}});await tx.transaction.create({data:{userId:u.id,type:'SPEND',amount:-cost,description:`business-upgrade:${b.name}:L${row.level+1}`}});return tx.playerBusiness.update({where:{id:row.id},data:{level:{increment:1},staff:{increment:2},reputation:{increment:4}}})});return NextResponse.json({ok:true,business:upgraded,cash:save.cash-cost});}
if(action==='hire'){const row=await prisma.playerBusiness.findFirst({where:{userId:u.id,businessId:b.id}});if(!row)return err('You do not own this business.',403);const cost=150000; if(save.cash<cost)return err('Hiring costs ₦150,000.',402);const hired=await prisma.$transaction(async tx=>{await tx.save.update({where:{userId:u.id},data:{cash:{decrement:cost}}});return tx.playerBusiness.update({where:{id:row.id},data:{staff:{increment:1},expenses:{increment:cost}}})});return NextResponse.json({ok:true,business:hired,cash:save.cash-cost});}
return err('Unknown action.',400);}
