ALTER TABLE "Save" ADD COLUMN IF NOT EXISTS "freeWill" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Save" ADD COLUMN IF NOT EXISTS "workBiz" TEXT;
ALTER TABLE "Save" ADD COLUMN IF NOT EXISTS "workJob" INTEGER;
ALTER TABLE "Save" ADD COLUMN IF NOT EXISTS "seenAt" TIMESTAMP(3);
