ALTER TABLE "Save" ADD COLUMN IF NOT EXISTS "drunk" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Save" ADD COLUMN IF NOT EXISTS "high" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Save" ADD COLUMN IF NOT EXISTS "intoxAt" TIMESTAMP(3);
